name: "Install"
description: "Setup Node.js and install dependencies using pnpm"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: "20"
        cache: "pnpm"

    - name: Install pnpm
      run: npm install -g pnpm
      shell: bash

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
