name: Lint code
on: [workflow_call]
jobs:
  lint:
    runs-on: unbutu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: "./.github/actions/install"

      - name: TSC check
        run: pnpm tsc

      - name: Linting check
        run: pnpm lint

      - name: Formatting check
        run: pnpm format
