name: Test and coverage

on: [workflow_call]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: "./.github/actions/install"

      - name: Test
        run: pnpm test
      # TODO - add coverage step
